--한줄 주석 부호 
/* 
여러 줄 주석 부호

*/ 
--데이터 저장공간 테이블 정의 
--DDL
CREATE TABLE MEMBER (
    ID VARCHAR2 (20) PRIMARY KEY, --NOT NULL + UNIQUE
    NAME VARCHAR2(30) NOT NULL, 
    PASSWORD VARCHAR2(200) NOT NULL,
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(300)
);
----
--DML
INSERT INTO MEMBER (ID, NAME, PASSWORD)
VALUES ('HONG','홍길동','1234');

--DCL 
COMMIT;
ROLLBACK; --임시 처리된 작업 취소

INSERT INTO MEMBER (ID, NAME, PASSWORD)
VALUES ('HONG2', '홍길동2', '1234');
COMMIT;
--키 중복입력시 : ORA-00001: unique constraint (MYSTUDY.SYS_C006999) violated
INSERT INTO MEMBER (ID, NAME, PASSWORD)
VALUES ('HONG2', '홍길동2', '1234');

--NOT NULL 데이터 미입력 오류 : ORA-01400: cannot insert NULL into ("MYSTUDY"."MEMBER"."PASSWORD")
INSERT INTO MEMBER (ID, NAME)
VALUES ('HONG3', '홍길동3');
------------------------------------
SELECT * FROM MEMBER;

