SELECT COUNT (*) AS CNT FROM GUEST;

SELECT NVL (MAX(SABUN), 0)+ 1111 AS SABUN FROM GUEST;

INSERT INTO GUEST
     (SABUN, NAME, REGDATE, PAY)
VALUES(:SABUN, :NAME, SYSDATE, :PAY)
;


UPDATE GUEST
    SET NAME = 'USER7', REGDATE = SYSDATE, PAY = 5000 
    WHERE SABUN = 1111
;

DELETE FROM GUEST WHERE ID = '1111';