
SELECT * FROM STUDENT
WHERE NAME LIKE '%김유신%'
;

UPDATE STUDENT
    SET KOR = 95, ENG=85, MATH =75
WHERE ID = '2021004'
;
ROLLBACK;

SELECT * FROM STUDENT;
--DELETE FROM STUDENT WHERE ID = '2021007';

ROLLBACK;


SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = '2021001'
;
--STATEMENT 방식
SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = '2021002'
;

--PREPARED 방식 
SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = :aaa
;


SELECT * FROM STUDENT;

SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = '2021001' OR '1' = '1'
;
--STATEMENT 는 데이터보안에 취약 
SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = ''; DROP TABLE STUDENT; SELECT A FROM DUAL WHERE '1' = '1'
;

SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = '9999' OR '1' = '1'
;

SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = :ID -- '9999' OR '1' = '1'
;

SELECT  ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = '2021008'
;

SELECT ID, NAME, KOR, ENG, MATH, TOT, AVG 
FROM STUDENT 
WHERE ID = ''; DROP TABLE STUDENT; SELECT A FROM DUAL WHERE '1' = '1'
;
SELECT * FROM STUDENT WHERE ID = '2021001';






